---
title: "Data_Preprocessing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#step 1 : Data Pre-processing to make a five matrix for finding eQTL related to expression after stroke

```{r}
#create SNP.txt file
#sort the AxiomGT1.calls_v2.csv for individual's name, try with smaller names.

setwd("C:/eQTL/R_eQTL_Stroke/eQTL_Stroke")
AxiomGT1.calls_v2 <- read.csv("C:/eQTL/SNP/SNP_calls_351_eQTL/AxiomGT1.calls_v2.csv", row.names = 1)
dim(AxiomGT1.calls_v2) #628679    351
library("dplyr")
AxiomGT1.calls_v2_sort <- AxiomGT1.calls_v2 %>% 
    select(sort(names(.)))
dim(AxiomGT1.calls_v2_sort) #628679    351
AxiomGT1.calls_v2_sort[AxiomGT1.calls_v2_sort == -1] <- NA # -1 in our data is equal missing data
save(AxiomGT1.calls_v2_sort, file = "../../Input_Output/AxiomGT1.calls_v2_sort.Rdata")
write.table(AxiomGT1.calls_v2_sort, file = "../../Input_Output/SNP.txt",col.names = T, sep = "\t")
```


```{r}
#create SNP_Location file
Axiom_BioBank1.na35.annot_v2 <- read.csv("C:/eQTL/SNP/SNP_calls_351_eQTL/Axiom_BioBank1.na35.annot_v2.csv", row.names = 1)
dim(Axiom_BioBank1.na35.annot_v2) # 718212     29
#subsetting the annotation file, to have only 628679 SNP data
Axiom_BioBank1.na35.annot_v2_small <- Axiom_BioBank1.na35.annot_v2[rownames(AxiomGT1.calls_v2_sort), ]
dim(Axiom_BioBank1.na35.annot_v2_small) #628679     29
Axiom_BioBank1.na35.annot_v2_small_v2 <- Axiom_BioBank1.na35.annot_v2_small[,c(4,5)] #dim 628679      2
library(dplyr)
df <- add_rownames(Axiom_BioBank1.na35.annot_v2_small_v2,"snpis") # convert rownames to first colname dim 628679 3
save(df,file = "../../Input_Output/SNP_Location.Rdata")
write.table(df, file = "../../Input_Output/SNP_Location.txt",col.names =  T , sep = "\t")
```


```{r}
#create GE.txt and Gene_Location.txt files
gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1 <- read.delim("C:/eQTL/GENE/Picked_Files/gene_expression_351/gene_expression_annotation_351.SST-RMA-GENE-FULL - Group 1.TXT", row.names=1)

colnames(gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1) <- sub(x = colnames(gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1), pattern = "_HTA*.*", replacement ="") #remove colnames's tail #dim 351
#sort based on colnames
gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort <- gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1 %>% 
    select(sort(names(.)))
dim(gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort) #70523   364
gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort_small <- gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort[,-c(1,3,4,5,6,7,8,11,12,13)] #Subet start and end with chr dim 70523 354

GE<- gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort_small[,c(-1,-2,-3)] # 70523   351
Gene_Location <- gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort_small[,c(1,2,3)]
write.csv(gene_expression_annotation_351.SST.RMA.GENE.FULL...Group.1_sort_small, file = "../../Input_Output/GE_Location.txt",col.names = F, sep = "\t")
write.table(GE, file = "../../Input_Output/GE.txt",col.names = T, sep = "\t") #removing 2995 genes, these genes are control genes.
write.table(Gene_Location, file = "../../Input_Output/Gene_Location.txt",col.names =T, sep = "\t")
```

```{r}
#create covariates file
#file names is "SNP_PC1_PC2_Pc3_plink"
#first load primary covariates file

COVARIATES <- read.delim("C:/eQTL/Primary_Files/COVARIATES.txt", header=FALSE, row.names=1)
COVARIATES_t <- t(COVARIATES)
dim(COVARIATES) #6 351
dim(COVARIATES_t) #351 6
#need to add colname for final_sample_list to merge name file with COVARIATES file
final_sample_list <- read.csv("C:/eQTL/Primary_Files/final_sample_list.csv")
dim(final_sample_list) #351 3
merge <- merge(COVARIATES_t, final_sample_list, by = "id", all.x = TRUE, sort =TRUE) #now I get name for each id in COVARIATES file
dim(merge) #351 8
write.csv(merge, file = "../../Input_Output/Covariates_Merge.txt",col.names = F)
merge_v2 <- merge[,c(7,2,3,4,5,6)]
dim(merge_v2) #351 6
#sort based in the fisrt colname (name)
merge_v2_sort <- merge_v2[order( merge_v2[,1] ),]
write.table(merge_v2_sort, file = "../../Input_Output/Covariates_Merge_v2_sort.txt",col.names = F,sep = "\t")
```

```{r}
#add first three PCs into Covariates_Merge.txt file
SNP_PC1_PC2_PC3_Plink_v2 <- read.delim("C:/eQTL/R_eQTL_Stroke/Input_Output/SNP_PC1_PC2_PC3_Plink_v2.txt", header=FALSE)
dim(SNP_PC1_PC2_PC3_Plink_v2) #352 4

```

```{r}
#combine the SNP_PC1_PC2_PC3_Plink_v2 and merge_v2_sort files
#import Covariates_Final.txt as a covariates matrix including first three PCs
Covariates_Final <- read.delim("C:/eQTL/R_eQTL_Stroke/Input_Output/Covariates_Final.txt", row.names=1)
dim(Covariates_Final) #351 8 
```

```{r}
#this library can order multiple column data frame based on specific column
#install.packages("psych")
# data <- read.table(file = "../../Input_Output/Gene_Location.txt")
# library("psych")
# data_order <- dfOrder(data,c(3))

```

